// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do:
//
//    using EverythingHouse.WpfApp.Models;
//
//    var reply = Reply.FromJson(jsonString);
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Globalization;


namespace EverythingHouse.WpfApp.Models;

/// <summary>
/// 回复模型
/// </summary>
public class Reply
{
    [JsonPropertyName("content")]
    public string Content { get; set; } = null!;

    [JsonPropertyName("createTime")]
    public string CreateTime { get; set; } = null!;

    [JsonPropertyName("delTag")]
    public long DelTag { get; set; }

    [JsonPropertyName("id")]
    public long Id { get; set; }

    [JsonPropertyName("isAccepted")]
    public bool IsAccepted { get; set; }

    [JsonPropertyName("likes")]
    public long Likes { get; set; }

    [JsonPropertyName("postId")]
    public long PostId { get; set; }

    [JsonPropertyName("updateTime")]
    public string UpdateTime { get; set; } = null!;

    [JsonPropertyName("userId")]
    public long UserId { get; set; }
}
